spring:
    application:
        name: config-demo
    profiles:
        active: default
    config:
        import: optional:configserver:http://localhost:8888

management:
    endpoints:
        web:
            exposure:
                include: refresh

build:
    id: 101
    version: 1.2.3
    name: "Default-Build"
    type: "Default Build"
