spring:
    application:
        name: config-demo
    profiles:
        active: prod
    config:
        import: optional:configserver:http://localhost:8888

build:
    id: 101
    version: 1.2.3
    name: "Default-Build"
    type: "Default Build"
